# prometheus.yml
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'pi_mainnet'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'pi-supernode'
