FROM prom/prometheus:v2.30.3

# Copy the Prometheus configuration file
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expose the Prometheus port
EXPOSE 9090

# Set the default command
CMD ["--config.file=/etc/prometheus/prometheus.yml"]
