# Notifications service configuration

# Message broker configuration
messageBroker:
  type: rabbitmq
  host: message_broker
  port: 5672
  username: rabbitmq
  password: password

# Logging configuration
logging:
  level: info
  file: /var/log/notifications.log

# Server configuration
server:
  host: localhost
  port: 3005
