# User management service configuration

# Database configuration
database:
  host: localhost
  port: 5432
  name: user_management
  user: user_management
  password: password

# Logging configuration
logging:
  level: info
  file: /var/log/user-management.log

# Server configuration
server:
  host: localhost
  port: 3004
