FROM elasticsearch:7.16.1

# Set environment variables
ENV discovery.type=single-node

# Expose the Elasticsearch ports
EXPOSE 9200
EXPOSE 9300

# Set the default command
CMD ["-E", "discovery.type=single-node", "-E", "xpack.security.enabled=false"]
